#!/usr/bin/env node
// Downloads animated sprites for every species in the game and converts them into sprite strips
// in assets/sprites/ (git-ignored), then writes assets/sprites/sprites.js so the game uses them.
// The images stay on your machine: never commit them.
//
//   node tools/fetch-sprites.js                       # all species, normal + shiny
//   node tools/fetch-sprites.js --only pikachu,eevee  # just these
//   node tools/fetch-sprites.js --normal "https://example.org/{name}.gif" --shiny "https://example.org/shiny/{name}.gif"
//
// URL templates understand {name} (species id, e.g. "mr-mime"), {Name} (display name), {dex} (25) and {dex3} (025).
// Behind a proxy, Node 22+ needs NODE_USE_ENV_PROXY=1 to honour HTTPS_PROXY.
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const { decodeGif } = require('./lib/gif');
const { buildSheet } = require('./lib/sheet');

const ROOT = path.join(__dirname, '..');
const DEFAULTS = {
  normal: 'https://projectpokemon.org/images/normal-sprite/{name}.gif',
  shiny: 'https://projectpokemon.org/images/shiny-sprite/{name}.gif',
  out: path.join(ROOT, 'assets', 'sprites'),
  maxFrames: 48, maxSize: 128, concurrency: 4, delay: 150, facing: 'front'
};

function parseArgs(argv) {
  const o = Object.assign({}, DEFAULTS);
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i], next = () => argv[++i];
    if (a === '--only') o.only = next().split(',').map(s => s.trim()).filter(Boolean);
    else if (a === '--normal') o.normal = next();
    else if (a === '--shiny') o.shiny = next();
    else if (a === '--no-shiny') o.shiny = null;
    else if (a === '--out') o.out = path.resolve(next());
    else if (a === '--max-frames') o.maxFrames = Number(next());
    else if (a === '--max-size') o.maxSize = Number(next());
    else if (a === '--concurrency') o.concurrency = Number(next());
    else if (a === '--delay') o.delay = Number(next());
    else if (a === '--facing') o.facing = next();
    else if (a === '-h' || a === '--help') { console.log(fs.readFileSync(__filename, 'utf8').split('\n').slice(1, 11).join('\n').replace(/^\/\/ ?/gm, '')); process.exit(0); }
    else { console.error('Unknown option: ' + a); process.exit(2); }
  }
  return o;
}

function loadSpecies() {
  const ctx = { window: {}, console, Math };
  vm.createContext(ctx);
  for (const f of ['core/util.js', 'data/types.js', 'data/natures.js', 'data/moves.js', 'data/abilities.js', 'data/species.js'])
    vm.runInContext(fs.readFileSync(path.join(ROOT, 'js', f), 'utf8'), ctx, { filename: f });
  return ctx.window.TJP.SPECIES;
}

function urlFor(tpl, sp) {
  return tpl.replace(/\{name\}/g, sp.id).replace(/\{Name\}/g, encodeURIComponent(sp.name))
    .replace(/\{dex3\}/g, String(sp.dex).padStart(3, '0')).replace(/\{dex\}/g, String(sp.dex));
}

const sleep = ms => new Promise(r => setTimeout(r, ms));
async function download(url) {
  for (let attempt = 0; attempt < 3; attempt++) {
    try {
      const res = await fetch(url, { headers: { 'User-Agent': 'pokemon-jungle-tokyo sprite fetcher (personal use)' } });
      if (res.status === 404) return { missing: true };
      if (!res.ok) throw new Error('HTTP ' + res.status);
      return { data: Buffer.from(await res.arrayBuffer()) };
    } catch (e) {
      if (attempt === 2) return { error: e.cause ? `${e.message} (${e.cause.code || e.cause.message})` : e.message };
      await sleep(1000 * 2 ** attempt);
    }
  }
}

function convert(buf, file, o) {
  const isGif = buf.subarray(0, 3).toString('ascii') === 'GIF';
  if (!isGif) {
    if (buf.subarray(1, 4).toString('ascii') === 'PNG') { fs.writeFileSync(file, buf); return { frames: 1, fps: 0 }; }
    throw new Error('not a GIF or PNG (got ' + buf.subarray(0, 15).toString('latin1').replace(/[^\x20-\x7e]/g, '.') + ')');
  }
  const sheet = buildSheet(decodeGif(buf), { maxFrames: o.maxFrames, maxSize: o.maxSize });
  fs.writeFileSync(file, sheet.png);
  return { frames: sheet.frames, fps: sheet.fps };
}

function readManifest(file) {
  try {
    const ctx = { window: {} }; vm.createContext(ctx);
    vm.runInContext(fs.readFileSync(file, 'utf8'), ctx);
    return { ids: ctx.window.TJP_SPRITES || [], meta: ctx.window.TJP_SPRITE_META || {} };
  } catch (e) { return { ids: [], meta: {} }; }
}

function writeManifest(file, ids, meta, facing, source) {
  const body = `// Generated by tools/fetch-sprites.js on ${new Date().toISOString().slice(0, 10)} from ${source}.
// Lists the sprite files in this folder; it holds no artwork, so it is safe to commit.
// Delete this file's entries (or run \`git checkout assets/sprites/sprites.js\`) to go back to the built-in art.
window.TJP_SPRITES = ${JSON.stringify(ids)};
window.TJP_SPRITE_META = ${JSON.stringify(meta, null, 1).replace(/\n\s*/g, ' ')};
window.TJP_SPRITE_FACING = ${JSON.stringify(facing)};
`;
  fs.writeFileSync(file, body);
}

async function main() {
  const o = parseArgs(process.argv.slice(2));
  const S = loadSpecies();
  const ids = (o.only || Object.keys(S)).filter(id => { if (!S[id]) console.warn(`Unknown species "${id}", skipping`); return !!S[id]; });
  fs.mkdirSync(o.out, { recursive: true });
  const manifestFile = path.join(o.out, 'sprites.js');
  const manifest = readManifest(manifestFile);
  const ok = [], missing = [], failed = [];
  let next = 0;
  async function worker() {
    while (next < ids.length) {
      const id = ids[next++], sp = S[id];
      const variants = [['normal', o.normal, `${id}.png`]].concat(o.shiny ? [['shiny', o.shiny, `${id}-shiny.png`]] : []);
      const meta = {};
      for (const [kind, tpl, name] of variants) {
        const url = urlFor(tpl, sp);
        const r = await download(url);
        if (r.missing) { if (kind === 'normal') missing.push(id); continue; }
        if (r.error) { failed.push(`${id} (${kind}): ${r.error}`); continue; }
        try {
          const info = convert(r.data, path.join(o.out, name), o);
          if (kind === 'normal') Object.assign(meta, { fps: info.fps, frames: info.frames });
          else meta.shiny = true;
        } catch (e) { failed.push(`${id} (${kind}): ${e.message}`); }
        await sleep(o.delay);
      }
      if (meta.frames) {
        ok.push(id);
        manifest.meta[id] = meta;
        if (!manifest.ids.includes(id)) manifest.ids.push(id);
        process.stdout.write(`✓ ${sp.name.padEnd(11)} ${String(meta.frames).padStart(2)} frames${meta.shiny ? ' + shiny' : ''}\n`);
      }
    }
  }
  await Promise.all(Array.from({ length: Math.max(1, o.concurrency) }, worker));
  if (ok.length) writeManifest(manifestFile, manifest.ids.sort(), manifest.meta, o.facing, new URL(o.normal.replace(/\{[^}]+\}/g, 'x')).host || o.normal);
  console.log(`\n${ok.length} sprites saved to ${path.relative(process.cwd(), o.out) || '.'}`);
  if (missing.length) console.log(`Not found (404): ${missing.join(', ')}`);
  if (failed.length) console.log(`Failed:\n  ${failed.join('\n  ')}`);
  if (!ok.length) process.exitCode = 1;
}

if (require.main === module) main();
module.exports = { urlFor, convert };
